// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7wcOtkYqVtbnQypiziCoVeBPQa86LgTE',
    appId: '1:1063386889599:web:16b1dd0da3f73c1d6fae4a',
    messagingSenderId: '1063386889599',
    projectId: 'prjpab2-si61-2327240029',
    authDomain: 'prjpab2-si61-2327240029.firebaseapp.com',
    storageBucket: 'prjpab2-si61-2327240029.firebasestorage.app',
    measurementId: 'G-ML27LXPV6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRfJLutUZdqTpNCi6Y8-DU_KaJpWsg8Fo',
    appId: '1:1063386889599:android:db56e6ff35a641286fae4a',
    messagingSenderId: '1063386889599',
    projectId: 'prjpab2-si61-2327240029',
    storageBucket: 'prjpab2-si61-2327240029.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuewHK3ozjiDXh5DfP-TDbxBOiMgAJDyc',
    appId: '1:1063386889599:ios:fa247bccba99fe576fae4a',
    messagingSenderId: '1063386889599',
    projectId: 'prjpab2-si61-2327240029',
    storageBucket: 'prjpab2-si61-2327240029.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuewHK3ozjiDXh5DfP-TDbxBOiMgAJDyc',
    appId: '1:1063386889599:ios:fa247bccba99fe576fae4a',
    messagingSenderId: '1063386889599',
    projectId: 'prjpab2-si61-2327240029',
    storageBucket: 'prjpab2-si61-2327240029.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7wcOtkYqVtbnQypiziCoVeBPQa86LgTE',
    appId: '1:1063386889599:web:a7658d7ba66983c26fae4a',
    messagingSenderId: '1063386889599',
    projectId: 'prjpab2-si61-2327240029',
    authDomain: 'prjpab2-si61-2327240029.firebaseapp.com',
    storageBucket: 'prjpab2-si61-2327240029.firebasestorage.app',
    measurementId: 'G-Z1G3DFJ4S0',
  );
}
